CREATE TABLE UNIDADE_PENAL (
    ID_UP INTEGER,
    NOME_UP VARCHAR(50),
    ENDERECO VARCHAR(50),
    NUMERO VARCHAR(30),
    BAIRRO VARCHAR(50),
    COMPLEMENTO VARCHAR(50),
    CEP VARCHAR(8),
    ID_CIDADE INTEGER,
    FONE VARCHAR(50),
    FAX VARCHAR(50),
    CONTATO VARCHAR(50),
    FOTO VARCHAR(16386),
    CAPITAL VARCHAR(30),
    REGIAO VARCHAR(50),
    SIGLA VARCHAR(50),
    REGIME VARCHAR(30),
    GENERO VARCHAR(30),
    EMAIL VARCHAR(100),
    CNPJ VARCHAR(30),
    CHAVE_MIGRACAO VARCHAR(100),
    QTDE_VAGA INTEGER
);

ALTER TABLE UNIDADE_PENAL ADD CONSTRAINT PK_UNIDADE_PENAL PRIMARY KEY (ID_UP);
ALTER TABLE UNIDADE_PENAL ADD CONSTRAINT FK_UNIDADE_PENAL_1 FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE (ID_CIDADE);